# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - meta_engineer_arm_controller

  meta_engineer_arm_controller:
    type: FollowJointTrajectory
    joints:
      - l_Base001__to__l_Link006
      - l_Link006__to__l_Link007
      - l_Link007__to__l_Link008
      - l_Link008__to__l_Link009
      - l_Link009__to__l_Link010
      - l_Link010__to__l_Link011
      - l_Link011__to__l_Claw001